version: '3.8'

services:
  db_dev:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootdev
      POSTGRES_DB: dev_db
    ports:
      - "5431:5432"
    volumes:
      - dev_db_data:/var/lib/postgresql/data

  db_prod:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootprod
      POSTGRES_DB: prod_db
    ports:
      - "5434:5432"
    volumes:
      - prod_db_data:/var/lib/postgresql/data

volumes:
  dev_db_data:
  prod_db_data: