version: "3.9"

services:
  db_prod:
    image: postgres:15
    restart: always
    env_file: .env.prod
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./sql/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql

  # web:
  #   build: .
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  #   env_file: .env.prod
  #   depends_on:
  #     - db
  #   ports:
  #     - "8001:8000"

volumes:
  postgres_data_prod:
